Remove artifact name for imx6ull
mendersoftware/meta-mender-community pull request #211
Opened 2021-01-22 22:41 UTC by Goz3rr

I'm assuming @rickyricksanchez used this snippet from my [mender hub topic](https://hub.mender.io/t/ubifs-ecc-errors-after-adding-mender-to-toradex-imx6ull-image/1767) about a year ago, and it got merged in #205.

I don't believe there's a functional need for the name to be there, as it's already set to `release-1` in the main local.conf.append anyways.

2021-03-24 09:28 UTC, Goz3rr commented
bump

2021-03-24 09:37 UTC, lluiscampos requested changes
@Goz3rr Thanks for the bump. The change looks good to me, so I'll follow-up to get it reviewed and merged.

You need to sign your work for our CI checks to pass. See [here](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#sign-your-work).

2021-03-24 09:48 UTC, rickyricksanchez commented
> I'm assuming @rickyricksanchez used this snippet from my [mender hub topic](https://hub.mender.io/t/ubifs-ecc-errors-after-adding-mender-to-toradex-imx6ull-image/1767) about a year ago, and it got merged in #205.

Assumption is correct, I made a mix of several snippets and is true, this line got accidentally merged. 
I fully agree with the change.

2021-03-24 09:49 UTC, rickyricksanchez approved these changes

2021-04-06 11:23 UTC, lluiscampos commented
> You need to sign your work for our CI checks to pass. See [here](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#sign-your-work).

ping @Goz3rr :)

2021-04-06 11:59 UTC, Goz3rr commented
I don't mind signing off on the commit however I'd rather not have to deal with my real name for personal reasons.

2021-04-06 14:55 UTC, lluiscampos commented
> I don't mind signing off on the commit however I'd rather not have to deal with my real name for personal reasons.

All right, I respect that.

I have resubmitted your patch at #224.

2021-04-06 14:55 UTC, closed without merging

2021-04-07 07:47 UTC, Goz3rr commented
Awesome, thanks 👍